### ISSUE TITLE
Back End: User Authentication Routes

### ISSUE THREAD

**Issue by Sarthak-Oza** [tlg-23-08-sde-3/23-08-JavaScriptProject-Team1-BackEnd#12]

**Comment by Sarthak-Oza** [comment]
# Subtasks

- [ ] User signup route
- [ ] User signin route
- [ ] password encryption and jwt
