### ISSUE TITLE
Back End: Node Server and MongoDB Setup

### ISSUE THREAD

**Issue by Sarthak-Oza** [tlg-23-08-sde-3/23-08-JavaScriptProject-Team1-BackEnd#2]

**Comment by Sarthak-Oza** [comment]
## Subtasks

- [ ] Create express server
- [ ] Create mongoDB and connect it with mongoose. 
- [ ] Use route to structure routes for auth and landing pages
